# Generated by Django 2.0.5 on 2018-06-28 07:13

from django.db import migrations
from users.models import User


def create_superuser(apps, schema_editor):
    if not User.objects.filter(username='admin').exists():
        User.objects.create_user(
            username='admin',
            email='admin@admin.net',
            password='Qw12345%',
            is_active=True,
            is_superuser=True,
            is_staff=True,
            phone_number_local='',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180604_1313'),
    ]

    operations = [migrations.RunPython(create_superuser), ]
