version: '2'

services:

  celery_worker:
    build:
      context: ../
      dockerfile: docker/django/django_30.Dockerfile
    command: python docker/celery_worker/run.py
    depends_on:
      - redis
    restart: always

  celery_beat:
    build:
      context: ../
      dockerfile: docker/django/django_30.Dockerfile
    command: python docker/celery_beat/run.py
    depends_on:
      - redis
    restart: always

  watcher:
    build:
      context: ../
      dockerfile: docker/django/django_30.Dockerfile
    command: python docker/watcher/run.py 
    volumes_from:
      - django
    restart: always

  event_watcher:
    build:
      context: ../
      dockerfile: docker/django/django_30.Dockerfile
    command: python docker/event_watcher/run.py 
    volumes_from:
      - django
    restart: always

  redis:
    image: redis:4.0.10-alpine
    restart: always

  nginx:
    container_name: nginx-container
    links:
      - django
    build: 
      context: ../
      dockerfile: docker/nginx/nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - django
    restart: always
      
  django:
    build:
      context: ../
      dockerfile: docker/django/django_30.Dockerfile
    depends_on:
      - redis
    volumes:
      - /crm
      - /usr/local/lib/python3.5/site-packages/django/
      - /mnt/disk/16b225cd-f7fe-464f-9344-0e59ce397f8c/monitor:/crm/call_center/crm/static/files/monitor
      - /mnt/disk/16b225cd-f7fe-464f-9344-0e59ce397f8c/voicemail/default/0080:/crm/call_center/crm/static/files/0080
    restart: always