# Generated by Django 2.0.5 on 2018-06-04 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_remove_call_groups_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_type_task', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип проблемы до изменения')),
                ('old_description_task', models.TextField(blank=True, null=True, verbose_name='Описание прорблемы до изменения')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Call')),
                ('old_executor_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_executor_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
