# Generated by Django 2.0.5 on 2018-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_logcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcall',
            name='log_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время звонка'),
        ),
    ]
