# Generated by Django 2.0.5 on 2018-06-05 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_logcall_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcall',
            name='user_changed_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_changed_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
