# Generated by Django 2.0.5 on 2018-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180718_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='unique_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Идентификатор активного звонка и истории'),
        ),
    ]
